; The ESP32-S3 is a powerful microcontroller from Espressif, designed for IoT applications. It features a dual-core Xtensa LX7 processor, Wi-Fi and Bluetooth connectivity, and a range of peripherals. The ESP32-S3 is ideal for applications that require high performance and low power consumption, such as smart home devices, wearables, and industrial automation.
[env:ESP32S3]

; The ESP32-S3 is a powerful microcontroller from Espressif, designed for IoT applications. It features a dual-core Xtensa LX7 processor, Wi-Fi and Bluetooth connectivity, and a range of peripherals. The ESP32-S3 is ideal for applications that require high performance and low power consumption, such as smart home devices, wearables, and industrial automation.
platform = espressif32

; The ESP32-S3 DevKitC-1 is a development board based on the ESP32-S3 microcontroller. It provides a convenient platform for prototyping and developing applications using the ESP32-S3. The board includes various peripherals and interfaces, such as USB, GPIOs, and support for Wi-Fi and Bluetooth connectivity, making it suitable for a wide range of IoT projects.
board = esp32-s3-devkitc-1-n16r8v

; The ESP-IDF (Espressif IoT Development Framework) is the official development framework for the ESP32 series of microcontrollers. It provides a comprehensive set of libraries, tools, and APIs for developing applications on ESP32 devices. The ESP-IDF supports features such as Wi-Fi, Bluetooth, and various peripherals, making it a powerful choice for building IoT applications with the ESP32-S3.
framework = espidf

; For serial monitoring
monitor_speed = 115200

; External library dependencies
lib_deps = ${core.lib_deps}

; Tell PIO to look INSIDE the downloaded repo for sub-libraries
; This assumes the sub-libraries are in a folder named 'lib' or 'src' inside the repo
lib_extra_dirs = 
    ; .pio/libdeps/ESP32S3/External/lib

; Filter your local project source
build_src_filter = 
    -<*> 
    +<ESP32S3/**>

build_flags =
    -D ENV_ESP32
    -D ENV_ESP32S3N16
    -I include
    ; TODO: FREERTOS is causing the build to fail this needs addressed before merging
    -I .pio/libdeps/ESP32S3/External/lib/ESP32S3
    -I .pio/libdeps/STM32F7/External/lib/FreeRTOS/include
    -I .pio/libdeps/STM32F7/External/lib/FreeRTOS/CMSIS_RTOS_V2
    -I .pio/libdeps/STM32F7/External/lib/FreeRTOS/portable/gcc/ARM_CM7/r0p1
    -I .pio/libdeps/STM32F7/External/lib/FreeRTOS