[platformio]
description = Provide ESP32-S3 and STM32F7 support for the Formula Hybrid project, allowing for development and testing on both platforms with shared code and libraries.
boards_dir = boards
extra_configs =
    platformio_stm32f7.ini
    platformio_esp32s3.ini

[core]
lib_deps = 