; The STMicroelectronics STM32F7 series is a family of high-performance microcontrollers based on the ARM Cortex-M7 core. These microcontrollers are designed for applications that require advanced processing capabilities, such as multimedia, graphics, and real-time control. The STM32F7 series offers a wide range of features, including high-speed interfaces, large memory options, and various peripherals, making it suitable for complex embedded systems.
[env:STM32F7]
; The STMicroelectronics STM32F7 series is a family of high-performance microcontrollers based on the ARM Cortex-M7 core. These microcontrollers are designed for applications that require advanced processing capabilities, such as multimedia, graphics, and real-time control. The STM32F7 series offers a wide range of features, including high-speed interfaces, large memory options, and various peripherals, making it suitable for complex embedded systems.
platform = ststm32

; The Nucleo F767ZI is a development board based on the STM32F767ZI microcontroller, which is part of the STM32F7 series. It features a powerful ARM Cortex-M7 core, making it suitable for high-performance applications. The board includes various peripherals and interfaces, such as USB, Ethernet, and multiple GPIOs, making it a versatile choice for embedded development.
board = nucleo_f767zi

; The STM32Cube framework is used for STM32 development, it provides a comprehensive set of libraries and tools for working with STM32 microcontrollers, including hardware abstraction layers (HAL), middleware, and example projects.
framework = stm32cube

;This python script is necessary for enabling floating point precision for FreeRTOS on an STM32
extra_scripts = pre:force_fpu.py 

;If you don't add this line, your build will use the default config header which has missing definitions
board_build.stm32cube.custom_config_header = yes 

;Highly recommend you determine your cpu for your board and add this line (alleviates potential build issues later on)
board_build.f_cpu = cortex-m7 

;If you don't have this good luck getting GPIO or FreeRTOS to work predictably, if you don't it will try the default and when you upload nothing will happen
board_build.ldscript = STM32F767ZITX_FLASH.ld 

;This is necessary for allowing board specific files to be put into the lib folder i.e.: lib\STM32F7
lib_archive = no 

;For serial monitoring
monitor_speed = 115200 

;You can get away without, but eases the use of debugging. WARNING, do not use this unless an actual stlink is used for connecting and programming these (almost all dev boards have one)
upload_protocol = stlink 

; External library dependencies
lib_deps = ${core.lib_deps}

; Tell PIO to look INSIDE the downloaded repo for sub-libraries
; This assumes the sub-libraries are in a folder named 'lib' or 'src' inside the repo
lib_extra_dirs = 
    .pio/libdeps/STM32F7/External/lib

; Filter your local project source
build_src_filter = 
    -<*> 
    +<STM32F7/**>

; The -I means include, if you don't do that header files (.h) can get missed during build
; The -D means define, this is used for conditional compilation in the code, allowing you to write code that only compiles for certain environments
build_flags = 
    -D ENV_STM32
    -D ENV_STM32F7
    -I include/STM32F7
    -I .pio/libdeps/STM32F7/External/lib/STM32F7
    -I .pio/libdeps/STM32F7/External/include
    -I .pio/libdeps/STM32F7/External/lib/STM32F7/include
    -I .pio/libdeps/STM32F7/External/lib/STM32F7/src
    -I .pio/libdeps/STM32F7/External/lib/FreeRTOS/include
    -I .pio/libdeps/STM32F7/External/lib/FreeRTOS/CMSIS_RTOS_V2
    -I .pio/libdeps/STM32F7/External/lib/FreeRTOS/portable/gcc/ARM_CM7/r0p1
    -I .pio/libdeps/STM32F7/External/lib/FreeRTOS